// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: sale_products.proto

package sale_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaleProductServiceClient is the client API for SaleProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaleProductServiceClient interface {
	Create(ctx context.Context, in *CreateSaleProductRequest, opts ...grpc.CallOption) (*CreateSaleProductResponse, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetSaleProductResponse, error)
	List(ctx context.Context, in *ListSaleProductRequest, opts ...grpc.CallOption) (*ListSaleProductResponse, error)
	Update(ctx context.Context, in *UpdateSaleProductRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Response, error)
}

type saleProductServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaleProductServiceClient(cc grpc.ClientConnInterface) SaleProductServiceClient {
	return &saleProductServiceClient{cc}
}

func (c *saleProductServiceClient) Create(ctx context.Context, in *CreateSaleProductRequest, opts ...grpc.CallOption) (*CreateSaleProductResponse, error) {
	out := new(CreateSaleProductResponse)
	err := c.cc.Invoke(ctx, "/sale_service.SaleProductService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleProductServiceClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetSaleProductResponse, error) {
	out := new(GetSaleProductResponse)
	err := c.cc.Invoke(ctx, "/sale_service.SaleProductService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleProductServiceClient) List(ctx context.Context, in *ListSaleProductRequest, opts ...grpc.CallOption) (*ListSaleProductResponse, error) {
	out := new(ListSaleProductResponse)
	err := c.cc.Invoke(ctx, "/sale_service.SaleProductService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleProductServiceClient) Update(ctx context.Context, in *UpdateSaleProductRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sale_service.SaleProductService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleProductServiceClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sale_service.SaleProductService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleProductServiceServer is the server API for SaleProductService service.
// All implementations must embed UnimplementedSaleProductServiceServer
// for forward compatibility
type SaleProductServiceServer interface {
	Create(context.Context, *CreateSaleProductRequest) (*CreateSaleProductResponse, error)
	Get(context.Context, *IdRequest) (*GetSaleProductResponse, error)
	List(context.Context, *ListSaleProductRequest) (*ListSaleProductResponse, error)
	Update(context.Context, *UpdateSaleProductRequest) (*Response, error)
	Delete(context.Context, *IdRequest) (*Response, error)
	mustEmbedUnimplementedSaleProductServiceServer()
}

// UnimplementedSaleProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSaleProductServiceServer struct {
}

func (UnimplementedSaleProductServiceServer) Create(context.Context, *CreateSaleProductRequest) (*CreateSaleProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSaleProductServiceServer) Get(context.Context, *IdRequest) (*GetSaleProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSaleProductServiceServer) List(context.Context, *ListSaleProductRequest) (*ListSaleProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSaleProductServiceServer) Update(context.Context, *UpdateSaleProductRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSaleProductServiceServer) Delete(context.Context, *IdRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSaleProductServiceServer) mustEmbedUnimplementedSaleProductServiceServer() {}

// UnsafeSaleProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaleProductServiceServer will
// result in compilation errors.
type UnsafeSaleProductServiceServer interface {
	mustEmbedUnimplementedSaleProductServiceServer()
}

func RegisterSaleProductServiceServer(s grpc.ServiceRegistrar, srv SaleProductServiceServer) {
	s.RegisterService(&SaleProductService_ServiceDesc, srv)
}

func _SaleProductService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaleProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleProductServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sale_service.SaleProductService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleProductServiceServer).Create(ctx, req.(*CreateSaleProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleProductService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleProductServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sale_service.SaleProductService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleProductServiceServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleProductService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSaleProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleProductServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sale_service.SaleProductService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleProductServiceServer).List(ctx, req.(*ListSaleProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleProductService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSaleProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleProductServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sale_service.SaleProductService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleProductServiceServer).Update(ctx, req.(*UpdateSaleProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleProductService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleProductServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sale_service.SaleProductService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleProductServiceServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaleProductService_ServiceDesc is the grpc.ServiceDesc for SaleProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaleProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sale_service.SaleProductService",
	HandlerType: (*SaleProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SaleProductService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SaleProductService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SaleProductService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SaleProductService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SaleProductService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sale_products.proto",
}
