// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: branch_product.proto

package branch_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BranchProductServiceClient is the client API for BranchProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BranchProductServiceClient interface {
	Create(ctx context.Context, in *CreateBranchProductRequest, opts ...grpc.CallOption) (*CreateBranchProductResponse, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetBranchProductResponse, error)
	List(ctx context.Context, in *ListBranchProductRequest, opts ...grpc.CallOption) (*ListBranchProductResponse, error)
	Update(ctx context.Context, in *UpdateBranchProductRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Response, error)
}

type branchProductServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBranchProductServiceClient(cc grpc.ClientConnInterface) BranchProductServiceClient {
	return &branchProductServiceClient{cc}
}

func (c *branchProductServiceClient) Create(ctx context.Context, in *CreateBranchProductRequest, opts ...grpc.CallOption) (*CreateBranchProductResponse, error) {
	out := new(CreateBranchProductResponse)
	err := c.cc.Invoke(ctx, "/branch_service.BranchProductService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchProductServiceClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetBranchProductResponse, error) {
	out := new(GetBranchProductResponse)
	err := c.cc.Invoke(ctx, "/branch_service.BranchProductService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchProductServiceClient) List(ctx context.Context, in *ListBranchProductRequest, opts ...grpc.CallOption) (*ListBranchProductResponse, error) {
	out := new(ListBranchProductResponse)
	err := c.cc.Invoke(ctx, "/branch_service.BranchProductService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchProductServiceClient) Update(ctx context.Context, in *UpdateBranchProductRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/branch_service.BranchProductService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchProductServiceClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/branch_service.BranchProductService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranchProductServiceServer is the server API for BranchProductService service.
// All implementations must embed UnimplementedBranchProductServiceServer
// for forward compatibility
type BranchProductServiceServer interface {
	Create(context.Context, *CreateBranchProductRequest) (*CreateBranchProductResponse, error)
	Get(context.Context, *IdRequest) (*GetBranchProductResponse, error)
	List(context.Context, *ListBranchProductRequest) (*ListBranchProductResponse, error)
	Update(context.Context, *UpdateBranchProductRequest) (*Response, error)
	Delete(context.Context, *IdRequest) (*Response, error)
	mustEmbedUnimplementedBranchProductServiceServer()
}

// UnimplementedBranchProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBranchProductServiceServer struct {
}

func (UnimplementedBranchProductServiceServer) Create(context.Context, *CreateBranchProductRequest) (*CreateBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBranchProductServiceServer) Get(context.Context, *IdRequest) (*GetBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBranchProductServiceServer) List(context.Context, *ListBranchProductRequest) (*ListBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBranchProductServiceServer) Update(context.Context, *UpdateBranchProductRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBranchProductServiceServer) Delete(context.Context, *IdRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBranchProductServiceServer) mustEmbedUnimplementedBranchProductServiceServer() {}

// UnsafeBranchProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BranchProductServiceServer will
// result in compilation errors.
type UnsafeBranchProductServiceServer interface {
	mustEmbedUnimplementedBranchProductServiceServer()
}

func RegisterBranchProductServiceServer(s grpc.ServiceRegistrar, srv BranchProductServiceServer) {
	s.RegisterService(&BranchProductService_ServiceDesc, srv)
}

func _BranchProductService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchProductServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/branch_service.BranchProductService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchProductServiceServer).Create(ctx, req.(*CreateBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchProductService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchProductServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/branch_service.BranchProductService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchProductServiceServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchProductService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchProductServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/branch_service.BranchProductService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchProductServiceServer).List(ctx, req.(*ListBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchProductService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchProductServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/branch_service.BranchProductService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchProductServiceServer).Update(ctx, req.(*UpdateBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchProductService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchProductServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/branch_service.BranchProductService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchProductServiceServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BranchProductService_ServiceDesc is the grpc.ServiceDesc for BranchProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BranchProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "branch_service.BranchProductService",
	HandlerType: (*BranchProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BranchProductService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BranchProductService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BranchProductService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BranchProductService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BranchProductService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "branch_product.proto",
}
