// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: tariff.proto

package sale

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TariffType int32

const (
	TariffType_FIXED   TariffType = 0
	TariffType_PERCENT TariffType = 1
)

// Enum value maps for TariffType.
var (
	TariffType_name = map[int32]string{
		0: "FIXED",
		1: "PERCENT",
	}
	TariffType_value = map[string]int32{
		"FIXED":   0,
		"PERCENT": 1,
	}
)

func (x TariffType) Enum() *TariffType {
	p := new(TariffType)
	*p = x
	return p
}

func (x TariffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TariffType) Descriptor() protoreflect.EnumDescriptor {
	return file_tariff_proto_enumTypes[0].Descriptor()
}

func (TariffType) Type() protoreflect.EnumType {
	return &file_tariff_proto_enumTypes[0]
}

func (x TariffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TariffType.Descriptor instead.
func (TariffType) EnumDescriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{0}
}

type Tariff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,3,opt,name=type,proto3,enum=sale.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *Tariff) Reset() {
	*x = Tariff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariff) ProtoMessage() {}

func (x *Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tariff.ProtoReflect.Descriptor instead.
func (*Tariff) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{0}
}

func (x *Tariff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tariff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tariff) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *Tariff) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *Tariff) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type CreateTariffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,2,opt,name=type,proto3,enum=sale.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,3,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,4,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *CreateTariffRequest) Reset() {
	*x = CreateTariffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTariffRequest) ProtoMessage() {}

func (x *CreateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTariffRequest.ProtoReflect.Descriptor instead.
func (*CreateTariffRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTariffRequest) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *CreateTariffRequest) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *CreateTariffRequest) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type CreateTariffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariff *Tariff `protobuf:"bytes,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
}

func (x *CreateTariffResponse) Reset() {
	*x = CreateTariffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTariffResponse) ProtoMessage() {}

func (x *CreateTariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTariffResponse.ProtoReflect.Descriptor instead.
func (*CreateTariffResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type GetTariffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariff *Tariff `protobuf:"bytes,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
}

func (x *GetTariffResponse) Reset() {
	*x = GetTariffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTariffResponse) ProtoMessage() {}

func (x *GetTariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTariffResponse.ProtoReflect.Descriptor instead.
func (*GetTariffResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{3}
}

func (x *GetTariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type UpdateTariffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,3,opt,name=type,proto3,enum=sale.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *UpdateTariffRequest) Reset() {
	*x = UpdateTariffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTariffRequest) ProtoMessage() {}

func (x *UpdateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTariffRequest.ProtoReflect.Descriptor instead.
func (*UpdateTariffRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTariffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTariffRequest) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *UpdateTariffRequest) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *UpdateTariffRequest) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type ListTariffsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariffs []*Tariff `protobuf:"bytes,1,rep,name=tariffs,proto3" json:"tariffs,omitempty"`
	Count   int32     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListTariffsResponse) Reset() {
	*x = ListTariffsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTariffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTariffsResponse) ProtoMessage() {}

func (x *ListTariffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTariffsResponse.ProtoReflect.Descriptor instead.
func (*ListTariffsResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{5}
}

func (x *ListTariffsResponse) GetTariffs() []*Tariff {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

func (x *ListTariffsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_tariff_proto protoreflect.FileDescriptor

var file_tariff_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x73, 0x61, 0x6c, 0x65, 0x1a, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12,
	0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73,
	0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x22, 0x39, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x22, 0xaf, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73,
	0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x63, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72,
	0x43, 0x61, 0x72, 0x64, 0x22, 0x53, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x74,
	0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x61, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x07, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x24, 0x0a, 0x0a, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x58, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x52, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x32,
	0xa7, 0x02, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x47, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x12, 0x19, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73,
	0x61, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x0f, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x61, 0x6c,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tariff_proto_rawDescOnce sync.Once
	file_tariff_proto_rawDescData = file_tariff_proto_rawDesc
)

func file_tariff_proto_rawDescGZIP() []byte {
	file_tariff_proto_rawDescOnce.Do(func() {
		file_tariff_proto_rawDescData = protoimpl.X.CompressGZIP(file_tariff_proto_rawDescData)
	})
	return file_tariff_proto_rawDescData
}

var file_tariff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tariff_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tariff_proto_goTypes = []interface{}{
	(TariffType)(0),              // 0: sale.TariffType
	(*Tariff)(nil),               // 1: sale.Tariff
	(*CreateTariffRequest)(nil),  // 2: sale.CreateTariffRequest
	(*CreateTariffResponse)(nil), // 3: sale.CreateTariffResponse
	(*GetTariffResponse)(nil),    // 4: sale.GetTariffResponse
	(*UpdateTariffRequest)(nil),  // 5: sale.UpdateTariffRequest
	(*ListTariffsResponse)(nil),  // 6: sale.ListTariffsResponse
	(*IdRequest)(nil),            // 7: sale.IdRequest
	(*ListRequest)(nil),          // 8: sale.ListRequest
	(*Response)(nil),             // 9: sale.Response
}
var file_tariff_proto_depIdxs = []int32{
	0,  // 0: sale.Tariff.type:type_name -> sale.TariffType
	0,  // 1: sale.CreateTariffRequest.type:type_name -> sale.TariffType
	1,  // 2: sale.CreateTariffResponse.tariff:type_name -> sale.Tariff
	1,  // 3: sale.GetTariffResponse.tariff:type_name -> sale.Tariff
	0,  // 4: sale.UpdateTariffRequest.type:type_name -> sale.TariffType
	1,  // 5: sale.ListTariffsResponse.tariffs:type_name -> sale.Tariff
	2,  // 6: sale.TariffService.CreateTariff:input_type -> sale.CreateTariffRequest
	7,  // 7: sale.TariffService.Get:input_type -> sale.IdRequest
	8,  // 8: sale.TariffService.List:input_type -> sale.ListRequest
	5,  // 9: sale.TariffService.Update:input_type -> sale.UpdateTariffRequest
	7,  // 10: sale.TariffService.Delete:input_type -> sale.IdRequest
	3,  // 11: sale.TariffService.CreateTariff:output_type -> sale.CreateTariffResponse
	4,  // 12: sale.TariffService.Get:output_type -> sale.GetTariffResponse
	6,  // 13: sale.TariffService.List:output_type -> sale.ListTariffsResponse
	9,  // 14: sale.TariffService.Update:output_type -> sale.Response
	9,  // 15: sale.TariffService.Delete:output_type -> sale.Response
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tariff_proto_init() }
func file_tariff_proto_init() {
	if File_tariff_proto != nil {
		return
	}
	file_branch_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tariff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tariff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTariffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTariffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTariffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTariffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTariffsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tariff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tariff_proto_goTypes,
		DependencyIndexes: file_tariff_proto_depIdxs,
		EnumInfos:         file_tariff_proto_enumTypes,
		MessageInfos:      file_tariff_proto_msgTypes,
	}.Build()
	File_tariff_proto = out.File
	file_tariff_proto_rawDesc = nil
	file_tariff_proto_goTypes = nil
	file_tariff_proto_depIdxs = nil
}
